#!/usr/bin/env bash

# Bundles the SconeStudio.app/ directory created by the dirtree step into a
# single `.dmg` file that users can download + install easily
#
# Requires `create-dmg` to bundle the dir up

set -xeuo pipefail
source "$( dirname ${BASH_SOURCE} )/build_config"

installer_name="SCONE-${SCONE_VERSION}"
dmg_name="${installer_name}-macOS.dmg"
app_name="SCONE.app"

# create-dmg fails if target already exists
rm -f "${SCONE_BUILD_DIR}/${dmg_name}"

./create-dmg/create-dmg \
    --volicon "${SCONE_BUILD_DIR}/${app_name}/Contents/MacOS/resources/ui/scone_logo_256x256.icns" \
    --volname "Install ${installer_name}" \
    --icon "${SCONE_BUILD_DIR}/${app_name}" 0 0 \
    --icon-size 100 \
    --app-drop-link 200 0 \
    "${SCONE_BUILD_DIR}/${dmg_name}" \
    "${SCONE_BUILD_DIR}/${app_name}"
