#!/usr/bin/env bash

set -xeuo pipefail
source "$( dirname ${BASH_SOURCE} )/build_config"

if [[ "$OSTYPE" == "darwin"* ]]; then
    cmake_extra_args=(
        -DCMAKE_PREFIX_PATH="${OSG_INSTALL_PATH}/lib64;${QT5_BREW_PATH}"
        -DOSGQT_INCLUDE_DIR="${OSG_INSTALL_PATH}/lib64"
        -DOSGQT_LIBRARY_RELEASE="${OSG_INSTALL_PATH}/lib/libosgQt.dylib"
        -DSCONE_LUA=ON
        -DSCONE_PYTHON=ON
        -DPYBIND11_PYTHON_VERSION=3.9
        -DSCONE_OPENSIM_3=ON
        -DSCONE_HYFYDY=ON
        -DSCONE_SNEL=ON
        -DHFD_BUILD_BLUEPRINT=ON
        -DHFD_BUILD_SNEL=ON
        -DHFD_BUILD_PRECISION_DOUBLE=ON
        -DSCONE_STUDIO_CPACK=ON
        -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    )
else
    cmake_extra_args=(
        -DCMAKE_PREFIX_PATH="${OSG_INSTALL_PATH}/lib64"
        -DSCONE_LUA=ON
        -DSCONE_PYTHON=ON
        -DPYBIND11_PYTHON_VERSION=3.9
        -DSCONE_OPENSIM_3=ON
        -DSCONE_HYFYDY=ON
        -DSCONE_SNEL=ON
        -DHFD_BUILD_BLUEPRINT=ON
        -DHFD_BUILD_SNEL=ON
        -DHFD_BUILD_PRECISION_DOUBLE=ON
        -DHFD_STATIC_LIBRARY=ON
        -DHFD_CONFIGURATION_NAMESPACE=ON
        -DSCONE_STUDIO_CPACK=ON
        -DSCONE_STUDIO_CPACK_DEBIAN=${SCONE_CREATE_DEBIAN_PACKAGE}
   )
fi

# Update version
# cd ./scone
# ./tools/update_version.sh
# cd ..

mkdir -p "${SCONE_BUILD_DIR}"
cd "${SCONE_BUILD_DIR}"
cmake "${SCONE_REPOSITORY_DIR}" \
    -DOSG_DIR="${OSG_INSTALL_PATH}" \
    -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" \
    -DCMAKE_VERBOSE_MAKEFILE="${CMAKE_VERBOSE_MAKEFILE}" \
    -DCMAKE_INSTALL_PREFIX="${SCONE_INSTALL_DIR}" \
    -DOPENSIM_INSTALL_DIR="${OPENSIM3_INSTALL_PATH}" \
    -DOPENSIM_INCLUDE_DIR="${OPENSIM3_INSTALL_PATH}/sdk/include" \
    ${cmake_extra_args[@]}
    
cmake --build . --parallel "${NUM_BUILD_JOBS}" --target install
