on: [push]

jobs:
  build:
    name: Build
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v1

    - name: Get Brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    - name: Get Dependencies
      run: cd $GITHUB_WORKSPACE && ./tools/mac_1_get-dependencies

    - name: Build openscenegraph
      run: cd $GITHUB_WORKSPACE && ./tools/mac_2a_build-osg

    - name: Build simbody
      run: cd $GITHUB_WORKSPACE && ./tools/mac_2b_build-simbody

    - name: Build opensim3
      run: cd $GITHUB_WORKSPACE && ./tools/mac_2c_build-opensim3

    - name: Build OsgQt
      run: cd $GITHUB_WORKSPACE && ./tools/mac_2d_build-osgqt

    - name: Build SCONE
      run: cd $GITHUB_WORKSPACE && ./tools/mac_2e_build-scone
